stages:
  - build

build:
  stage: build
  image: docker.nwnx.io:443/nwnxee/unified:builder
  script:
    - CC="gcc -m32" CXX="g++ -m32" cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
    - make all
    - Scripts/packageNWScript.sh
  artifacts:
    paths:
      - Binaries/NWNX_*.*
      - Binaries/NWScript.zip
